# Generated by Django 4.1.7 on 2023-03-14 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_carmodels_cars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='serie',
        ),
        migrations.CreateModel(
            name='CarSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=100)),
                ('year', models.DateField(auto_now_add=True)),
                ('serienumber', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='cars.cars')),
            ],
        ),
    ]
