# Generated by Django 4.1.7 on 2023-03-14 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_cars_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='price',
        ),
    ]
