# Generated by Django 4.1.7 on 2023-03-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_remove_cars_image_carseries_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carseries',
            name='year',
            field=models.DateField(),
        ),
    ]
