# Generated by Django 4.1.7 on 2023-03-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_alter_carseries_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carseries',
            name='year',
            field=models.DateField(),
        ),
    ]
