# Generated by Django 4.1.7 on 2023-03-14 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_alter_carseries_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carseries',
            old_name='serienumber',
            new_name='modelnumber',
        ),
    ]
