# Generated by Django 4.1.7 on 2023-03-14 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_alter_cars_options_alter_carseries_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='published_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cars',
            name='updated_date',
            field=models.DateTimeField(),
        ),
    ]
