# Generated by Django 4.1.7 on 2023-03-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_alter_cars_published_date_alter_cars_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
