# Generated by Django 4.1.7 on 2023-03-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_alter_cars_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
