# Generated by Django 4.1.7 on 2023-03-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0018_alter_carseries_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name': 'car manufacturer', 'verbose_name_plural': 'cars'},
        ),
        migrations.AlterModelOptions(
            name='carseries',
            options={'verbose_name': 'car data', 'verbose_name_plural': 'car series'},
        ),
        migrations.AddField(
            model_name='cars',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carseries',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
