# Generated by Django 4.1.7 on 2023-03-15 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0019_alter_cars_options_alter_carseries_options_cars_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carseries',
            name='slug',
        ),
    ]
