# Generated by Django 4.1.7 on 2023-03-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0020_remove_carseries_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='active',
        ),
        migrations.AddField(
            model_name='carseries',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
