# Generated by Django 4.1.7 on 2023-03-15 17:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0024_alter_carseries_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
