# Generated by Django 4.1.7 on 2023-03-16 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0027_carseriescomments_delete_carseriecomments'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_publish', models.DateField(auto_now_add=True)),
                ('modelnums', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelnum', to='cars.carseries')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
        migrations.DeleteModel(
            name='CarSeriesComments',
        ),
    ]
