# Generated by Django 4.1.7 on 2023-03-16 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0029_carseriescomments_delete_seriecomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='carseriescomments',
            name='cars',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_car', to='cars.cars'),
        ),
    ]
