# Generated by Django 4.1.7 on 2023-03-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0031_alter_carseriescomments_cars'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarFroms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'form',
            },
        ),
        migrations.RemoveField(
            model_name='carseries',
            name='type',
        ),
        migrations.AddField(
            model_name='carseries',
            name='type',
            field=models.ManyToManyField(related_name='formalar', to='cars.carfroms'),
        ),
    ]
