# Generated by Django 4.1.7 on 2023-03-16 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0033_alter_carfroms_options_alter_carseries_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarFroms',
            new_name='CarForms',
        ),
    ]
