# Generated by Django 4.1.7 on 2023-03-16 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0035_alter_carforms_options_carseriescomments_car_serie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carseriescomments',
            name='car_serie',
        ),
        migrations.RemoveField(
            model_name='carseriescomments',
            name='modelnumbers',
        ),
        migrations.AlterField(
            model_name='carseriescomments',
            name='cars',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_car', to='cars.carseries'),
        ),
    ]
