# Generated by Django 4.1.7 on 2023-03-16 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0036_remove_carseriescomments_car_serie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carseriescomments',
            name='car_serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serie_of_car', to='cars.carseries'),
        ),
        migrations.AddField(
            model_name='carseriescomments',
            name='modelnumbers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modelnum', to='cars.carseries'),
        ),
        migrations.AlterField(
            model_name='carseriescomments',
            name='cars',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_car', to='cars.cars'),
        ),
    ]
