# Generated by Django 4.1.7 on 2023-03-16 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0038_remove_carseriescomments_car_serie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carseriescomments',
            name='cars',
        ),
    ]
